site_name: Web3 Tech Stack
site_description: 'Documentation for the Web3 Technology Stack'
site_author: 'Web3 Foundation'
site_url: 'https://w3f.github.io/web3/'

theme:
  name: 'material'
  palette:
    primary: 'deep orange'
    accent: 'deep orange'
  logo: 'images/logo.svg'
  
extra_css:
  - 'stylesheets/extra.css'

nav:
  - Home: index.md
  - Layer 0: layer_0/index.md
  - Layer 1: layer_1/index.md
  - Layer 2: layer_2/index.md
  - Layer 3: layer_3/index.md
  - Layer 4: layer_4/index.md

extra:
  social:
    - type: 'github'
      link: 'https://github.com/w3f'
    - type: 'twitter'
      link: 'https://twitter.com/web3foundation'
    - type: 'medium'
      link: 'https://medium.com/web3foundation'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
        permalink: true
